version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'main'

  backend:
    image: node:16-alpine
    restart: "no"
    working_dir: "/app"
    command: sh -c "npm install && npm run develop"
    volumes:
      - ./backend:/app/
    ports:
      - 3001:3001
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: 'mysql'
  frontend:
    image: node:16-alpine
    restart: "no"
    working_dir: "/app"
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app/
    ports:
      - 3000:3000
    depends_on:
      - backend
